data_root: /sc-projects/sc-proj-cc06-ag-ki-radiologie/prostate-foundation/PICAI_registered/t2_hist_matched
dataset_json: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/dataset/PI-RADS_data.json
num_classes: !!int 4
mil_mode: att_trans
tile_count: !!int 24
tile_size: !!int 64
depth: !!int 3
use_heatmap: !!bool True
workers: !!int 4
epochs: !!int 100
batch_size: !!int 8
optim_lr: !!float 2e-4
weight_decay: !!float 1e-5
amp: !!bool True
wandb: !!bool True




