data_root: /sc-projects/sc-proj-cc06-ag-ki-radiologie/pirad_model_test_PICAI/registered/t2_hist_matched/
dataset_json: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/dataset/PICAI_cspca.json
num_classes: !!int 4
mil_mode: att_trans
tile_count: !!int 24
tile_size: !!int 64
depth: !!int 3
use_heatmap: !!bool True
workers: !!int 6
checkpoint_pirads: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/logs/pirads_training/model_47.pt
epochs: !!int 80
batch_size: !!int 8
optim_lr: !!float 2e-5




