name: CI

on:
  push:
    paths:
      - '**/*.py'

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # Speeds up subsequent runs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CI Suite
        run: make check


  deploy-to-hf:
    needs: quality-assurance # CRITICAL: Only runs if 'test' passes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # Enable if you are using large files

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # Replace with your HF username and Space name
          HF_USERNAME: "anirudh0410"
          SPACE_NAME: "WSA_Prostate"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Add Hugging Face as a remote
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          
          # Force push to the Space
          git push --force space main
